name: JD_Auto_Beans

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 4,16 * * *

env:
  sckey: ${{ secrets.sckey }}
  cookies: ${{ secrets.cookies }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Run install
        run: npm install

      - name: Run Script
        run: node index.js
